/* SPDX-License-Identifier: GPL-2.0-only */

#include "m3_backend_metal_dense_internal.h"

NSString *m3_metal_dense_kernel_source(void)
{
    NSString *matrices =
        @"kernel void m3_embedding(\n"
         "    device const uchar* ids [[buffer(0)]],\n"
         "    device const uchar* table [[buffer(1)]],\n"
         "    device uchar* output [[buffer(2)]],\n"
         "    constant M3ViewParameters& ids_view [[buffer(3)]],\n"
         "    constant M3ViewParameters& table_view [[buffer(4)]],\n"
         "    constant M3ViewParameters& output_view [[buffer(5)]],\n"
         "    uint gid [[thread_position_in_grid]]) {\n"
         "  ulong flat = ulong(gid);\n"
         "  if (flat >= output_view.element_count) return;\n"
         "  ulong channels = table_view.shape[1];\n"
         "  ulong token = flat / channels;\n"
         "  ulong channel = flat % channels;\n"
         "  ulong ids_offset = m3_view_logical_offset(ids_view, token);\n"
         "  int id = m3_load_i32(ids + ids_offset);\n"
         "  ulong table_flat = ulong(id) * channels + channel;\n"
         "  ulong table_offset =\n"
         "    m3_view_logical_offset(table_view, table_flat);\n"
         "  ulong output_offset =\n"
         "    m3_view_contiguous_offset(output_view, flat);\n"
         "  float value = m3_load_float(table + table_offset,\n"
         "                              table_view.dtype);\n"
         "  m3_store_float(output + output_offset, output_view.dtype,\n"
         "                 value);\n"
         "}\n"
         "kernel void m3_matmul(\n"
         "    device const uchar* left [[buffer(0)]],\n"
         "    device const uchar* right [[buffer(1)]],\n"
         "    device uchar* output [[buffer(2)]],\n"
         "    constant M3ViewParameters& left_view [[buffer(3)]],\n"
         "    constant M3ViewParameters& right_view [[buffer(4)]],\n"
         "    constant M3ViewParameters& output_view [[buffer(5)]],\n"
         "    uint gid [[thread_position_in_grid]]) {\n"
         "  ulong flat = ulong(gid);\n"
         "  if (flat >= output_view.element_count) return;\n"
         "  ulong inner = left_view.shape[1];\n"
         "  ulong columns = right_view.shape[1];\n"
         "  ulong row = flat / columns;\n"
         "  ulong column = flat % columns;\n"
         "  volatile float sum = 0.0f;\n"
         "  for (ulong index = 0; index < inner; ++index) {\n"
         "    ulong left_flat = row * inner + index;\n"
         "    ulong right_flat = index * columns + column;\n"
         "    ulong left_offset =\n"
         "      m3_view_logical_offset(left_view, left_flat);\n"
         "    ulong right_offset =\n"
         "      m3_view_logical_offset(right_view, right_flat);\n"
         "    float left_value =\n"
         "      m3_load_float(left + left_offset, left_view.dtype);\n"
         "    float right_value =\n"
         "      m3_load_float(right + right_offset, right_view.dtype);\n"
         "    volatile float product = left_value * right_value;\n"
         "    sum = sum + product;\n"
         "  }\n"
         "  ulong output_offset =\n"
         "    m3_view_contiguous_offset(output_view, flat);\n"
         "  m3_store_float(output + output_offset, output_view.dtype,\n"
         "                 sum);\n"
         "}\n"
         "kernel void m3_matmul_zero(\n"
         "    device uchar* output [[buffer(0)]],\n"
         "    constant M3ViewParameters& output_view [[buffer(1)]],\n"
         "    uint gid [[thread_position_in_grid]]) {\n"
         "  ulong flat = ulong(gid);\n"
         "  if (flat >= output_view.element_count) return;\n"
         "  ulong output_offset =\n"
         "    m3_view_contiguous_offset(output_view, flat);\n"
         "  m3_store_float(output + output_offset, output_view.dtype,\n"
         "                 0.0f);\n"
         "}\n";
    NSString *linear =
        @"kernel void m3_linear(\n"
         "    device const uchar* input [[buffer(0)]],\n"
         "    device const uchar* weight [[buffer(1)]],\n"
         "    device const uchar* bias [[buffer(2)]],\n"
         "    device uchar* output [[buffer(3)]],\n"
         "    constant M3ViewParameters& input_view [[buffer(4)]],\n"
         "    constant M3ViewParameters& weight_view [[buffer(5)]],\n"
         "    constant M3ViewParameters& bias_view [[buffer(6)]],\n"
         "    constant M3ViewParameters& output_view [[buffer(7)]],\n"
         "    constant uint& has_bias [[buffer(8)]],\n"
         "    uint gid [[thread_position_in_grid]]) {\n"
         "  ulong flat = ulong(gid);\n"
         "  if (flat >= output_view.element_count) return;\n"
         "  ulong input_features = weight_view.shape[1];\n"
         "  ulong output_features = weight_view.shape[0];\n"
         "  ulong row = flat / output_features;\n"
         "  ulong output_feature = flat % output_features;\n"
         "  volatile float sum = 0.0f;\n"
         "  if (has_bias != 0u) {\n"
         "    ulong bias_offset =\n"
         "      m3_view_logical_offset(bias_view, output_feature);\n"
         "    sum = m3_load_float(bias + bias_offset, bias_view.dtype);\n"
         "  }\n"
         "  for (ulong input_feature = 0;\n"
         "       input_feature < input_features; ++input_feature) {\n"
         "    ulong input_flat = row * input_features + input_feature;\n"
         "    ulong weight_flat =\n"
         "      output_feature * input_features + input_feature;\n"
         "    ulong input_offset =\n"
         "      m3_view_logical_offset(input_view, input_flat);\n"
         "    ulong weight_offset =\n"
         "      m3_view_logical_offset(weight_view, weight_flat);\n"
         "    float input_value =\n"
         "      m3_load_float(input + input_offset, input_view.dtype);\n"
         "    float weight_value =\n"
         "      m3_load_float(weight + weight_offset, weight_view.dtype);\n"
         "    volatile float product = input_value * weight_value;\n"
         "    sum = sum + product;\n"
         "  }\n"
         "  ulong output_offset =\n"
         "    m3_view_contiguous_offset(output_view, flat);\n"
         "  m3_store_float(output + output_offset, output_view.dtype,\n"
         "                 sum);\n"
         "}\n";
    NSString *rms_norm =
        @"kernel void m3_rms_norm(\n"
         "    device const uchar* input [[buffer(0)]],\n"
         "    device const uchar* scale [[buffer(1)]],\n"
         "    device uchar* output [[buffer(2)]],\n"
         "    constant M3ViewParameters& input_view [[buffer(3)]],\n"
         "    constant M3ViewParameters& scale_view [[buffer(4)]],\n"
         "    constant M3ViewParameters& output_view [[buffer(5)]],\n"
         "    constant float& epsilon [[buffer(6)]],\n"
         "    uint gid [[thread_position_in_grid]]) {\n"
         "  ulong channels = input_view.shape[input_view.rank - 1u];\n"
         "  ulong row = ulong(gid);\n"
         "  if (row >= input_view.element_count / channels) return;\n"
         "  volatile float square_sum = 0.0f;\n"
         "  for (ulong channel = 0; channel < channels; ++channel) {\n"
         "    ulong flat = row * channels + channel;\n"
         "    ulong input_offset =\n"
         "      m3_view_logical_offset(input_view, flat);\n"
         "    float value =\n"
         "      m3_load_float(input + input_offset, input_view.dtype);\n"
         "    volatile float square = value * value;\n"
         "    square_sum = square_sum + square;\n"
         "  }\n"
         "  float mean_square = square_sum / float(channels);\n"
         "  float inverse_rms =\n"
         "    1.0f / metal::precise::sqrt(mean_square + epsilon);\n"
         "  for (ulong channel = 0; channel < channels; ++channel) {\n"
         "    ulong flat = row * channels + channel;\n"
         "    ulong input_offset =\n"
         "      m3_view_logical_offset(input_view, flat);\n"
         "    ulong scale_offset =\n"
         "      m3_view_logical_offset(scale_view, channel);\n"
         "    ulong output_offset =\n"
         "      m3_view_contiguous_offset(output_view, flat);\n"
         "    float value =\n"
         "      m3_load_float(input + input_offset, input_view.dtype);\n"
         "    float scale_value =\n"
         "      m3_load_float(scale + scale_offset, scale_view.dtype);\n"
         "    float normalized =\n"
         "      m3_round_float(input_view.dtype, value * inverse_rms);\n"
         "    float result = normalized * scale_value;\n"
         "    m3_store_float(output + output_offset, output_view.dtype,\n"
         "                   result);\n"
         "  }\n"
         "}\n";
    NSString *layer_norm =
        @"kernel void m3_layer_norm(\n"
         "    device const uchar* input [[buffer(0)]],\n"
         "    device const uchar* scale [[buffer(1)]],\n"
         "    device const uchar* bias [[buffer(2)]],\n"
         "    device uchar* output [[buffer(3)]],\n"
         "    constant M3ViewParameters& input_view [[buffer(4)]],\n"
         "    constant M3ViewParameters& scale_view [[buffer(5)]],\n"
         "    constant M3ViewParameters& bias_view [[buffer(6)]],\n"
         "    constant M3ViewParameters& output_view [[buffer(7)]],\n"
         "    constant float& epsilon [[buffer(8)]],\n"
         "    constant uint& has_bias [[buffer(9)]],\n"
         "    uint gid [[thread_position_in_grid]]) {\n"
         "  ulong channels = input_view.shape[input_view.rank - 1u];\n"
         "  ulong row = ulong(gid);\n"
         "  if (row >= input_view.element_count / channels) return;\n"
         "  volatile float sum = 0.0f;\n"
         "  for (ulong channel = 0; channel < channels; ++channel) {\n"
         "    ulong flat = row * channels + channel;\n"
         "    ulong input_offset =\n"
         "      m3_view_logical_offset(input_view, flat);\n"
         "    float value =\n"
         "      m3_load_float(input + input_offset, input_view.dtype);\n"
         "    sum = sum + value;\n"
         "  }\n"
         "  float mean = sum / float(channels);\n"
         "  volatile float variance_sum = 0.0f;\n"
         "  for (ulong channel = 0; channel < channels; ++channel) {\n"
         "    ulong flat = row * channels + channel;\n"
         "    ulong input_offset =\n"
         "      m3_view_logical_offset(input_view, flat);\n"
         "    float value =\n"
         "      m3_load_float(input + input_offset, input_view.dtype);\n"
         "    float centered = value - mean;\n"
         "    volatile float square = centered * centered;\n"
         "    variance_sum = variance_sum + square;\n"
         "  }\n"
         "  float mean_variance = variance_sum / float(channels);\n"
         "  float inverse_standard_deviation =\n"
         "    1.0f / metal::precise::sqrt(mean_variance + epsilon);\n"
         "  for (ulong channel = 0; channel < channels; ++channel) {\n"
         "    ulong flat = row * channels + channel;\n"
         "    ulong input_offset =\n"
         "      m3_view_logical_offset(input_view, flat);\n"
         "    ulong scale_offset =\n"
         "      m3_view_logical_offset(scale_view, channel);\n"
         "    ulong output_offset =\n"
         "      m3_view_contiguous_offset(output_view, flat);\n"
         "    float value =\n"
         "      m3_load_float(input + input_offset, input_view.dtype);\n"
         "    float scale_value =\n"
         "      m3_load_float(scale + scale_offset, scale_view.dtype);\n"
         "    float centered = value - mean;\n"
         "    float normalized = centered * inverse_standard_deviation;\n"
         "    float result = normalized * scale_value;\n"
         "    if (has_bias != 0u) {\n"
         "      ulong bias_offset =\n"
         "        m3_view_logical_offset(bias_view, channel);\n"
         "      float bias_value =\n"
         "        m3_load_float(bias + bias_offset, bias_view.dtype);\n"
         "      result = result + bias_value;\n"
         "    }\n"
         "    m3_store_float(output + output_offset, output_view.dtype,\n"
         "                   result);\n"
         "  }\n"
         "}\n";
    NSString *rotary_activation =
        @"kernel void m3_rope(\n"
         "    device const uchar* input [[buffer(0)]],\n"
         "    device const uchar* cosines [[buffer(1)]],\n"
         "    device const uchar* sines [[buffer(2)]],\n"
         "    device uchar* output [[buffer(3)]],\n"
         "    constant M3ViewParameters& input_view [[buffer(4)]],\n"
         "    constant M3ViewParameters& cosines_view [[buffer(5)]],\n"
         "    constant M3ViewParameters& sines_view [[buffer(6)]],\n"
         "    constant M3ViewParameters& output_view [[buffer(7)]],\n"
         "    constant ulong& position_offset [[buffer(8)]],\n"
         "    constant uint& rotary_dimension [[buffer(9)]],\n"
         "    constant uint& mode [[buffer(10)]],\n"
         "    uint gid [[thread_position_in_grid]]) {\n"
         "  ulong vector = ulong(gid);\n"
         "  ulong depth = input_view.shape[3];\n"
         "  if (vector >= input_view.element_count / depth) return;\n"
         "  ulong position = vector % input_view.shape[2];\n"
         "  ulong table_row = position_offset + position;\n"
         "  ulong pair_count = ulong(rotary_dimension) / 2u;\n"
         "  for (ulong pair = 0; pair < pair_count; ++pair) {\n"
         "    ulong first_index = mode == 0u ? pair : pair * 2u;\n"
         "    ulong second_index = mode == 0u\n"
         "      ? pair + pair_count : pair * 2u + 1u;\n"
         "    ulong first_flat = vector * depth + first_index;\n"
         "    ulong second_flat = vector * depth + second_index;\n"
         "    ulong table_flat = table_row * pair_count + pair;\n"
         "    ulong first_offset =\n"
         "      m3_view_logical_offset(input_view, first_flat);\n"
         "    ulong second_offset =\n"
         "      m3_view_logical_offset(input_view, second_flat);\n"
         "    ulong cosine_offset =\n"
         "      m3_view_logical_offset(cosines_view, table_flat);\n"
         "    ulong sine_offset =\n"
         "      m3_view_logical_offset(sines_view, table_flat);\n"
         "    float first =\n"
         "      m3_load_float(input + first_offset, input_view.dtype);\n"
         "    float second =\n"
         "      m3_load_float(input + second_offset, input_view.dtype);\n"
         "    float cosine = m3_load_float(\n"
         "      cosines + cosine_offset, cosines_view.dtype);\n"
         "    float sine =\n"
         "      m3_load_float(sines + sine_offset, sines_view.dtype);\n"
         "    volatile float second_sine = second * sine;\n"
         "    volatile float first_sine = first * sine;\n"
         "    float rotated_first = metal::precise::fma(\n"
         "      first, cosine, -second_sine);\n"
         "    float rotated_second = metal::precise::fma(\n"
         "      second, cosine, first_sine);\n"
         "    ulong first_output =\n"
         "      m3_view_contiguous_offset(output_view, first_flat);\n"
         "    ulong second_output =\n"
         "      m3_view_contiguous_offset(output_view, second_flat);\n"
         "    m3_store_float(output + first_output, output_view.dtype,\n"
         "                   rotated_first);\n"
         "    m3_store_float(output + second_output, output_view.dtype,\n"
         "                   rotated_second);\n"
         "  }\n"
         "  for (ulong index = ulong(rotary_dimension); index < depth;\n"
         "       ++index) {\n"
         "    ulong flat = vector * depth + index;\n"
         "    ulong input_offset =\n"
         "      m3_view_logical_offset(input_view, flat);\n"
         "    ulong output_offset =\n"
         "      m3_view_contiguous_offset(output_view, flat);\n"
         "    float value =\n"
         "      m3_load_float(input + input_offset, input_view.dtype);\n"
         "    m3_store_float(output + output_offset, output_view.dtype,\n"
         "                   value);\n"
         "  }\n"
         "}\n"
         "kernel void m3_gated_silu(\n"
         "    device const uchar* gate [[buffer(0)]],\n"
         "    device const uchar* up [[buffer(1)]],\n"
         "    device uchar* output [[buffer(2)]],\n"
         "    constant M3ViewParameters& gate_view [[buffer(3)]],\n"
         "    constant M3ViewParameters& up_view [[buffer(4)]],\n"
         "    constant M3ViewParameters& output_view [[buffer(5)]],\n"
         "    uint gid [[thread_position_in_grid]]) {\n"
         "  ulong flat = ulong(gid);\n"
         "  if (flat >= output_view.element_count) return;\n"
         "  ulong gate_offset = m3_view_logical_offset(gate_view, flat);\n"
         "  ulong up_offset = m3_view_logical_offset(up_view, flat);\n"
         "  ulong output_offset =\n"
         "    m3_view_contiguous_offset(output_view, flat);\n"
         "  float gate_value =\n"
         "    m3_load_float(gate + gate_offset, gate_view.dtype);\n"
         "  float up_value =\n"
         "    m3_load_float(up + up_offset, up_view.dtype);\n"
         "  float denominator =\n"
         "    1.0f + metal::precise::exp(-gate_value);\n"
         "  float activation = gate_value / denominator;\n"
         "  activation = m3_round_float(gate_view.dtype, activation);\n"
         "  float result = activation * up_value;\n"
         "  m3_store_float(output + output_offset, output_view.dtype,\n"
         "                 result);\n"
         "}\n";

    NSString *source =
        [matrices stringByAppendingString:linear];

    source = [source stringByAppendingString:rms_norm];
    source = [source stringByAppendingString:layer_norm];
    return [source stringByAppendingString:rotary_activation];
}
