/* SPDX-License-Identifier: GPL-2.0-only */

#include "m3_backend_metal_convolution_internal.h"

NSString *m3_metal_convolution_kernel_source(void)
{
    NSString *convolution =
        @"#pragma clang fp contract(off)\n"
         "struct M3ConvolutionParameters {\n"
         "  ulong groups; ulong stride; ulong dilation; ulong pad_left;\n"
         "  uint has_bias; uint reserved;\n"
         "};\n"
         "static_assert(sizeof(M3ConvolutionParameters) == 40,\n"
         "  \"Metal convolution parameter size changed\");\n"
         "static_assert(alignof(M3ConvolutionParameters) == 8,\n"
         "  \"Metal convolution parameter alignment changed\");\n"
         "kernel void m3_conv1d(\n"
         "    device const uchar* input [[buffer(0)]],\n"
         "    device const uchar* weight [[buffer(1)]],\n"
         "    device const uchar* bias [[buffer(2)]],\n"
         "    device uchar* output [[buffer(3)]],\n"
         "    constant M3ViewParameters& input_view [[buffer(4)]],\n"
         "    constant M3ViewParameters& weight_view [[buffer(5)]],\n"
         "    constant M3ViewParameters& bias_view [[buffer(6)]],\n"
         "    constant M3ViewParameters& output_view [[buffer(7)]],\n"
         "    constant M3ConvolutionParameters& parameters [[buffer(8)]],\n"
         "    uint gid [[thread_position_in_grid]]) {\n"
         "  ulong flat = ulong(gid);\n"
         "  if (flat >= output_view.element_count) return;\n"
         "  ulong output_length = output_view.shape[2];\n"
         "  ulong output_channels = output_view.shape[1];\n"
         "  ulong output_position = flat % output_length;\n"
         "  ulong row = flat / output_length;\n"
         "  ulong output_channel = row % output_channels;\n"
         "  ulong batch = row / output_channels;\n"
         "  ulong input_channels = input_view.shape[1];\n"
         "  ulong input_length = input_view.shape[2];\n"
         "  ulong kernel_size = weight_view.shape[2];\n"
         "  ulong inputs_per_group = input_channels / parameters.groups;\n"
         "  ulong outputs_per_group =\n"
         "    output_channels / parameters.groups;\n"
         "  ulong group = output_channel / outputs_per_group;\n"
         "  ulong input_start = group * inputs_per_group;\n"
         "  ulong output_base = output_position * parameters.stride;\n"
         "  ulong input_batch_offset = input_view.byte_offset +\n"
         "    batch * input_view.byte_strides[0];\n"
         "  ulong weight_output_offset = weight_view.byte_offset +\n"
         "    output_channel * weight_view.byte_strides[0];\n"
         "  ulong input_position_stride = input_view.byte_strides[2];\n"
         "  ulong weight_kernel_stride = weight_view.byte_strides[2];\n"
         "  volatile float sum = 0.0f;\n"
         "  if (parameters.has_bias != 0u) {\n"
         "    ulong bias_offset =\n"
         "      m3_view_logical_offset(bias_view, output_channel);\n"
         "    sum = m3_load_float(bias + bias_offset, bias_view.dtype);\n"
         "  }\n"
         "  for (ulong input_in_group = 0;\n"
         "       input_in_group < inputs_per_group; ++input_in_group) {\n"
         "    ulong input_channel = input_start + input_in_group;\n"
         "    ulong input_channel_offset = input_batch_offset +\n"
         "      input_channel * input_view.byte_strides[1];\n"
         "    ulong weight_channel_offset = weight_output_offset +\n"
         "      input_in_group * weight_view.byte_strides[1];\n"
         "    for (ulong kernel_index = 0; kernel_index < kernel_size;\n"
         "         ++kernel_index) {\n"
         "      ulong kernel_position = kernel_index * parameters.dilation;\n"
         "      ulong padded_position = output_base + kernel_position;\n"
         "      if (padded_position < parameters.pad_left) continue;\n"
         "      ulong input_position =\n"
         "        padded_position - parameters.pad_left;\n"
         "      if (input_position >= input_length) continue;\n"
         "      ulong input_offset = input_channel_offset +\n"
         "        input_position * input_position_stride;\n"
         "      ulong weight_offset = weight_channel_offset +\n"
         "        kernel_index * weight_kernel_stride;\n"
         "      float input_value =\n"
         "        m3_load_float(input + input_offset, input_view.dtype);\n"
         "      float weight_value =\n"
         "        m3_load_float(weight + weight_offset, weight_view.dtype);\n"
         "      volatile float product = input_value * weight_value;\n"
         "      sum = sum + product;\n"
         "    }\n"
         "  }\n"
         "  ulong output_offset =\n"
         "    m3_view_contiguous_offset(output_view, flat);\n"
         "  m3_store_float(output + output_offset, output_view.dtype, sum);\n"
         "}\n";
    NSString *transpose =
        @"kernel void m3_conv_transpose1d(\n"
         "    device const uchar* input [[buffer(0)]],\n"
         "    device const uchar* weight [[buffer(1)]],\n"
         "    device const uchar* bias [[buffer(2)]],\n"
         "    device uchar* output [[buffer(3)]],\n"
         "    constant M3ViewParameters& input_view [[buffer(4)]],\n"
         "    constant M3ViewParameters& weight_view [[buffer(5)]],\n"
         "    constant M3ViewParameters& bias_view [[buffer(6)]],\n"
         "    constant M3ViewParameters& output_view [[buffer(7)]],\n"
         "    constant M3ConvolutionParameters& parameters [[buffer(8)]],\n"
         "    uint gid [[thread_position_in_grid]]) {\n"
         "  ulong flat = ulong(gid);\n"
         "  if (flat >= output_view.element_count) return;\n"
         "  ulong output_length = output_view.shape[2];\n"
         "  ulong output_channels = output_view.shape[1];\n"
         "  ulong output_position = flat % output_length;\n"
         "  ulong row = flat / output_length;\n"
         "  ulong output_channel = row % output_channels;\n"
         "  ulong batch = row / output_channels;\n"
         "  ulong input_channels = input_view.shape[1];\n"
         "  ulong input_length = input_view.shape[2];\n"
         "  ulong kernel_size = weight_view.shape[2];\n"
         "  ulong inputs_per_group = input_channels / parameters.groups;\n"
         "  ulong outputs_per_group =\n"
         "    output_channels / parameters.groups;\n"
         "  ulong group = output_channel / outputs_per_group;\n"
         "  ulong input_start = group * inputs_per_group;\n"
         "  ulong output_in_group = output_channel -\n"
         "    group * outputs_per_group;\n"
         "  ulong padded_output = output_position + parameters.pad_left;\n"
         "  ulong input_batch_offset = input_view.byte_offset +\n"
         "    batch * input_view.byte_strides[0];\n"
         "  ulong weight_output_offset = weight_view.byte_offset +\n"
         "    output_in_group * weight_view.byte_strides[1];\n"
         "  ulong input_position_stride = input_view.byte_strides[2];\n"
         "  ulong weight_kernel_stride = weight_view.byte_strides[2];\n"
         "  volatile float sum = 0.0f;\n"
         "  if (parameters.has_bias != 0u) {\n"
         "    ulong bias_offset =\n"
         "      m3_view_logical_offset(bias_view, output_channel);\n"
         "    sum = m3_load_float(bias + bias_offset, bias_view.dtype);\n"
         "  }\n"
         "  for (ulong input_in_group = 0;\n"
         "       input_in_group < inputs_per_group; ++input_in_group) {\n"
         "    ulong input_channel = input_start + input_in_group;\n"
         "    ulong input_channel_offset = input_batch_offset +\n"
         "      input_channel * input_view.byte_strides[1];\n"
         "    ulong weight_channel_offset = weight_output_offset +\n"
         "      input_channel * weight_view.byte_strides[0];\n"
         "    for (ulong kernel_index = 0; kernel_index < kernel_size;\n"
         "         ++kernel_index) {\n"
         "      ulong kernel_position = kernel_index * parameters.dilation;\n"
         "      if (kernel_position > padded_output) continue;\n"
         "      ulong distance = padded_output - kernel_position;\n"
         "      if (distance % parameters.stride != 0) continue;\n"
         "      ulong input_position = distance / parameters.stride;\n"
         "      if (input_position >= input_length) continue;\n"
         "      ulong input_offset = input_channel_offset +\n"
         "        input_position * input_position_stride;\n"
         "      ulong weight_offset = weight_channel_offset +\n"
         "        kernel_index * weight_kernel_stride;\n"
         "      float input_value =\n"
         "        m3_load_float(input + input_offset, input_view.dtype);\n"
         "      float weight_value =\n"
         "        m3_load_float(weight + weight_offset, weight_view.dtype);\n"
         "      volatile float product = input_value * weight_value;\n"
         "      sum = sum + product;\n"
         "    }\n"
         "  }\n"
         "  ulong output_offset =\n"
         "    m3_view_contiguous_offset(output_view, flat);\n"
         "  m3_store_float(output + output_offset, output_view.dtype, sum);\n"
         "}\n";
    NSString *resize =
        @"kernel void m3_nearest_resize1d(\n"
         "    device const uchar* input [[buffer(0)]],\n"
         "    device uchar* output [[buffer(1)]],\n"
         "    constant M3ViewParameters& input_view [[buffer(2)]],\n"
         "    constant M3ViewParameters& output_view [[buffer(3)]],\n"
         "    uint gid [[thread_position_in_grid]]) {\n"
         "  ulong input_length = input_view.shape[2];\n"
         "  ulong output_length = output_view.shape[2];\n"
         "  ulong rows = output_view.element_count / output_length;\n"
         "  ulong row = ulong(gid);\n"
         "  if (row >= rows) return;\n"
         "  ulong quotient = input_length / output_length;\n"
         "  ulong remainder_step = input_length % output_length;\n"
         "  ulong source = 0;\n"
         "  ulong remainder = 0;\n"
         "  for (ulong output_position = 0;\n"
         "       output_position < output_length; ++output_position) {\n"
         "    ulong input_flat = row * input_length + source;\n"
         "    ulong output_flat = row * output_length + output_position;\n"
         "    ulong input_offset =\n"
         "      m3_view_logical_offset(input_view, input_flat);\n"
         "    ulong output_offset =\n"
         "      m3_view_contiguous_offset(output_view, output_flat);\n"
         "    float value =\n"
         "      m3_load_float(input + input_offset, input_view.dtype);\n"
         "    m3_store_float(output + output_offset, output_view.dtype,\n"
         "                   value);\n"
         "    if (output_position + 1 < output_length) {\n"
         "      source += quotient;\n"
         "      if (remainder_step != 0) {\n"
         "        ulong threshold = output_length - remainder_step;\n"
         "        if (remainder >= threshold) {\n"
         "          remainder -= threshold; ++source;\n"
         "        } else {\n"
         "          remainder += remainder_step;\n"
         "        }\n"
         "      }\n"
         "    }\n"
         "  }\n"
         "}\n"
         "#pragma clang fp contract(on)\n";
    NSString *source = [convolution stringByAppendingString:transpose];

    return [source stringByAppendingString:resize];
}
