/* SPDX-License-Identifier: GPL-2.0-only */

#include "m3_backend_metal_dense_internal.h"

NSString *m3_metal_dense_kernel_source(void)
{
    NSString *embedding =
        @"kernel void m3_embedding(\n"
         "    device const uchar* ids [[buffer(0)]],\n"
         "    device const uchar* table [[buffer(1)]],\n"
         "    device uchar* output [[buffer(2)]],\n"
         "    constant M3ViewParameters& ids_view [[buffer(3)]],\n"
         "    constant M3ViewParameters& table_view [[buffer(4)]],\n"
         "    constant M3ViewParameters& output_view [[buffer(5)]],\n"
         "    uint gid [[thread_position_in_grid]]) {\n"
         "  ulong flat = ulong(gid);\n"
         "  if (flat >= output_view.element_count) return;\n"
         "  ulong channels = table_view.shape[1];\n"
         "  ulong token = flat / channels;\n"
         "  ulong channel = flat % channels;\n"
         "  ulong ids_offset = m3_view_logical_offset(ids_view, token);\n"
         "  int id = m3_load_i32(ids + ids_offset);\n"
         "  ulong table_flat = ulong(id) * channels + channel;\n"
         "  ulong table_offset =\n"
         "    m3_view_logical_offset(table_view, table_flat);\n"
         "  ulong output_offset =\n"
         "    m3_view_contiguous_offset(output_view, flat);\n"
         "  float value = m3_load_float(table + table_offset,\n"
         "                              table_view.dtype);\n"
         "  m3_store_float(output + output_offset, output_view.dtype,\n"
         "                 value);\n"
         "}\n";
    NSString *matrices =
        @"kernel void m3_matmul(\n"
         "    device const uchar* left [[buffer(0)]],\n"
         "    device const uchar* right [[buffer(1)]],\n"
         "    device uchar* output [[buffer(2)]],\n"
         "    constant M3ViewParameters& left_view [[buffer(3)]],\n"
         "    constant M3ViewParameters& right_view [[buffer(4)]],\n"
         "    constant M3ViewParameters& output_view [[buffer(5)]],\n"
         "    uint2 gid [[thread_position_in_grid]],\n"
         "    uint2 tid [[thread_position_in_threadgroup]],\n"
         "    uint2 group [[threadgroup_position_in_grid]]) {\n"
         "  threadgroup float left_tile[128];\n"
         "  threadgroup float right_tile[128];\n"
         "  threadgroup ulong left_bases[8];\n"
         "  threadgroup ulong right_bases[8];\n"
         "  ulong inner = left_view.shape[1];\n"
         "  ulong rows = left_view.shape[0];\n"
         "  ulong columns = right_view.shape[1];\n"
         "  ulong row = ulong(gid.y);\n"
         "  ulong column = ulong(gid.x);\n"
         "  uint local = tid.y * 8u + tid.x;\n"
         "  if (local < 8u) {\n"
         "    ulong base_row = ulong(group.y) * 8ul + ulong(local);\n"
         "    ulong base_column = ulong(group.x) * 8ul + ulong(local);\n"
         "    left_bases[local] = base_row < rows\n"
         "      ? m3_view_logical_offset(left_view, base_row * inner)\n"
         "      : 0ul;\n"
         "    right_bases[local] = base_column < columns\n"
         "      ? m3_view_logical_offset(right_view, base_column)\n"
         "      : 0ul;\n"
         "  }\n"
         "  threadgroup_barrier(mem_flags::mem_threadgroup);\n"
         "  ulong left_stride = left_view.byte_strides[1];\n"
         "  ulong right_stride = right_view.byte_strides[0];\n"
         "  volatile float sum = 0.0f;\n"
         "  for (ulong block_start = 0; block_start < inner;\n"
         "       block_start += 16ul) {\n"
         "    ulong block_count = min(16ul, inner - block_start);\n"
         "    for (uint load = local; load < 128u; load += 64u) {\n"
         "      uint tile_row = load / 16u;\n"
         "      uint tile_inner = load % 16u;\n"
         "      ulong global_row = ulong(group.y) * 8ul +\n"
         "        ulong(tile_row);\n"
         "      left_tile[load] = global_row < rows &&\n"
         "        ulong(tile_inner) < block_count\n"
         "        ? m3_load_float(left + left_bases[tile_row] +\n"
         "            (block_start + ulong(tile_inner)) * left_stride,\n"
         "            left_view.dtype)\n"
         "        : 0.0f;\n"
         "    }\n"
         "    for (uint load = local; load < 128u; load += 64u) {\n"
         "      uint tile_inner = load / 8u;\n"
         "      uint tile_column = load % 8u;\n"
         "      ulong global_column = ulong(group.x) * 8ul +\n"
         "        ulong(tile_column);\n"
         "      right_tile[load] = global_column < columns &&\n"
         "        ulong(tile_inner) < block_count\n"
         "        ? m3_load_float(right + right_bases[tile_column] +\n"
         "            (block_start + ulong(tile_inner)) * right_stride,\n"
         "            right_view.dtype)\n"
         "        : 0.0f;\n"
         "    }\n"
         "    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
         "    if (row < rows && column < columns) {\n"
         "      for (ulong index = 0; index < block_count; ++index) {\n"
         "        float left_value = left_tile[tid.y * 16u + uint(index)];\n"
         "        float right_value = right_tile[uint(index) * 8u + tid.x];\n"
         "        volatile float product = left_value * right_value;\n"
         "        sum = sum + product;\n"
         "      }\n"
         "    }\n"
         "    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
         "  }\n"
         "  if (row < rows && column < columns) {\n"
         "    ulong flat = row * columns + column;\n"
         "    ulong output_offset =\n"
         "      m3_view_contiguous_offset(output_view, flat);\n"
         "    m3_store_float(output + output_offset, output_view.dtype,\n"
         "                   sum);\n"
         "  }\n"
         "}\n"
         "kernel void m3_matmul_zero(\n"
         "    device uchar* output [[buffer(0)]],\n"
         "    constant M3ViewParameters& output_view [[buffer(1)]],\n"
         "    uint gid [[thread_position_in_grid]]) {\n"
         "  ulong flat = ulong(gid);\n"
         "  if (flat >= output_view.element_count) return;\n"
         "  ulong output_offset =\n"
         "    m3_view_contiguous_offset(output_view, flat);\n"
         "  m3_store_float(output + output_offset, output_view.dtype,\n"
         "                 0.0f);\n"
         "}\n";
    NSString *linear =
        @"kernel void m3_linear(\n"
         "    device const uchar* input [[buffer(0)]],\n"
         "    device const uchar* weight [[buffer(1)]],\n"
         "    device const uchar* bias [[buffer(2)]],\n"
         "    device uchar* output [[buffer(3)]],\n"
         "    constant M3ViewParameters& input_view [[buffer(4)]],\n"
         "    constant M3ViewParameters& weight_view [[buffer(5)]],\n"
         "    constant M3ViewParameters& bias_view [[buffer(6)]],\n"
         "    constant M3ViewParameters& output_view [[buffer(7)]],\n"
         "    constant uint& has_bias [[buffer(8)]],\n"
         "    uint2 gid [[thread_position_in_grid]],\n"
         "    uint2 tid [[thread_position_in_threadgroup]],\n"
         "    uint2 group [[threadgroup_position_in_grid]]) {\n"
         "  threadgroup float input_tile[128];\n"
         "  threadgroup float weight_tile[128];\n"
         "  threadgroup ulong input_bases[8];\n"
         "  threadgroup ulong weight_bases[8];\n"
         "  ulong input_features = weight_view.shape[1];\n"
         "  ulong output_features = weight_view.shape[0];\n"
         "  ulong rows = output_view.element_count / output_features;\n"
         "  ulong row = ulong(gid.y);\n"
         "  ulong output_feature = ulong(gid.x);\n"
         "  uint local = tid.y * 8u + tid.x;\n"
         "  if (local < 8u) {\n"
         "    ulong base_row = ulong(group.y) * 8ul + ulong(local);\n"
         "    ulong base_feature = ulong(group.x) * 8ul + ulong(local);\n"
         "    input_bases[local] = base_row < rows\n"
         "      ? m3_view_logical_offset(\n"
         "          input_view, base_row * input_features)\n"
         "      : 0ul;\n"
         "    weight_bases[local] = base_feature < output_features\n"
         "      ? m3_view_logical_offset(\n"
         "          weight_view, base_feature * input_features)\n"
         "      : 0ul;\n"
         "  }\n"
         "  threadgroup_barrier(mem_flags::mem_threadgroup);\n"
         "  ulong input_stride =\n"
         "    input_view.byte_strides[input_view.rank - 1u];\n"
         "  ulong weight_stride = weight_view.byte_strides[1];\n"
         "  volatile float sum = 0.0f;\n"
         "  if (row < rows && output_feature < output_features &&\n"
         "      has_bias != 0u) {\n"
         "    ulong bias_offset =\n"
         "      m3_view_logical_offset(bias_view, output_feature);\n"
         "    sum = m3_load_float(bias + bias_offset, bias_view.dtype);\n"
         "  }\n"
         "  for (ulong block_start = 0; block_start < input_features;\n"
         "       block_start += 16ul) {\n"
         "    ulong block_count = min(16ul, input_features - block_start);\n"
         "    for (uint load = local; load < 128u; load += 64u) {\n"
         "      uint tile_row = load / 16u;\n"
         "      uint tile_inner = load % 16u;\n"
         "      ulong global_row = ulong(group.y) * 8ul +\n"
         "        ulong(tile_row);\n"
         "      input_tile[load] = global_row < rows &&\n"
         "        ulong(tile_inner) < block_count\n"
         "        ? m3_load_float(input + input_bases[tile_row] +\n"
         "            (block_start + ulong(tile_inner)) * input_stride,\n"
         "            input_view.dtype)\n"
         "        : 0.0f;\n"
         "    }\n"
         "    for (uint load = local; load < 128u; load += 64u) {\n"
         "      uint tile_inner = load / 8u;\n"
         "      uint tile_feature = load % 8u;\n"
         "      ulong global_feature = ulong(group.x) * 8ul +\n"
         "        ulong(tile_feature);\n"
         "      weight_tile[load] = global_feature < output_features &&\n"
         "        ulong(tile_inner) < block_count\n"
         "        ? m3_load_float(weight + weight_bases[tile_feature] +\n"
         "            (block_start + ulong(tile_inner)) * weight_stride,\n"
         "            weight_view.dtype)\n"
         "        : 0.0f;\n"
         "    }\n"
         "    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
         "    if (row < rows && output_feature < output_features) {\n"
         "      for (ulong index = 0; index < block_count; ++index) {\n"
         "        float input_value = input_tile[tid.y * 16u + uint(index)];\n"
         "        float weight_value = weight_tile[uint(index) * 8u + tid.x];\n"
         "        volatile float product = input_value * weight_value;\n"
         "        sum = sum + product;\n"
         "      }\n"
         "    }\n"
         "    threadgroup_barrier(mem_flags::mem_threadgroup);\n"
         "  }\n"
         "  if (row < rows && output_feature < output_features) {\n"
         "    ulong flat = row * output_features + output_feature;\n"
         "    ulong output_offset =\n"
         "      m3_view_contiguous_offset(output_view, flat);\n"
         "    m3_store_float(output + output_offset, output_view.dtype,\n"
         "                   sum);\n"
         "  }\n"
         "}\n";
    NSString *rms_norm =
        @"kernel void m3_rms_norm(\n"
         "    device const uchar* input [[buffer(0)]],\n"
         "    device const uchar* scale [[buffer(1)]],\n"
         "    device uchar* output [[buffer(2)]],\n"
         "    constant M3ViewParameters& input_view [[buffer(3)]],\n"
         "    constant M3ViewParameters& scale_view [[buffer(4)]],\n"
         "    constant M3ViewParameters& output_view [[buffer(5)]],\n"
         "    constant float& epsilon [[buffer(6)]],\n"
         "    uint gid [[thread_position_in_grid]]) {\n"
         "  ulong channels = input_view.shape[input_view.rank - 1u];\n"
         "  ulong row = ulong(gid);\n"
         "  if (row >= input_view.element_count / channels) return;\n"
         "  ulong row_flat = row * channels;\n"
         "  ulong input_base =\n"
         "    m3_view_logical_offset(input_view, row_flat);\n"
         "  ulong input_stride =\n"
         "    input_view.byte_strides[input_view.rank - 1u];\n"
         "  ulong scale_base =\n"
         "    m3_view_logical_offset(scale_view, 0ul);\n"
         "  ulong scale_stride = scale_view.byte_strides[0];\n"
         "  volatile float square_sum = 0.0f;\n"
         "  for (ulong channel = 0; channel < channels; ++channel) {\n"
         "    ulong input_offset =\n"
         "      input_base + channel * input_stride;\n"
         "    float value =\n"
         "      m3_load_float(input + input_offset, input_view.dtype);\n"
         "    volatile float square = value * value;\n"
         "    square_sum = square_sum + square;\n"
         "  }\n"
         "  float mean_square = square_sum / float(channels);\n"
         "  float inverse_rms =\n"
         "    1.0f / metal::precise::sqrt(mean_square + epsilon);\n"
         "  for (ulong channel = 0; channel < channels; ++channel) {\n"
         "    ulong flat = row_flat + channel;\n"
         "    ulong input_offset =\n"
         "      input_base + channel * input_stride;\n"
         "    ulong scale_offset =\n"
         "      scale_base + channel * scale_stride;\n"
         "    ulong output_offset =\n"
         "      m3_view_contiguous_offset(output_view, flat);\n"
         "    float value =\n"
         "      m3_load_float(input + input_offset, input_view.dtype);\n"
         "    float scale_value =\n"
         "      m3_load_float(scale + scale_offset, scale_view.dtype);\n"
         "    float normalized =\n"
         "      m3_round_float(input_view.dtype, value * inverse_rms);\n"
         "    float result = normalized * scale_value;\n"
         "    m3_store_float(output + output_offset, output_view.dtype,\n"
         "                   result);\n"
         "  }\n"
         "}\n";
    NSString *layer_norm =
        @"kernel void m3_layer_norm(\n"
         "    device const uchar* input [[buffer(0)]],\n"
         "    device const uchar* scale [[buffer(1)]],\n"
         "    device const uchar* bias [[buffer(2)]],\n"
         "    device uchar* output [[buffer(3)]],\n"
         "    constant M3ViewParameters& input_view [[buffer(4)]],\n"
         "    constant M3ViewParameters& scale_view [[buffer(5)]],\n"
         "    constant M3ViewParameters& bias_view [[buffer(6)]],\n"
         "    constant M3ViewParameters& output_view [[buffer(7)]],\n"
         "    constant float& epsilon [[buffer(8)]],\n"
         "    constant uint& has_bias [[buffer(9)]],\n"
         "    uint gid [[thread_position_in_grid]]) {\n"
         "  ulong channels = input_view.shape[input_view.rank - 1u];\n"
         "  ulong row = ulong(gid);\n"
         "  if (row >= input_view.element_count / channels) return;\n"
         "  ulong row_flat = row * channels;\n"
         "  ulong input_base =\n"
         "    m3_view_logical_offset(input_view, row_flat);\n"
         "  ulong input_stride =\n"
         "    input_view.byte_strides[input_view.rank - 1u];\n"
         "  ulong scale_base =\n"
         "    m3_view_logical_offset(scale_view, 0ul);\n"
         "  ulong scale_stride = scale_view.byte_strides[0];\n"
         "  ulong bias_base = has_bias == 0u ? 0ul\n"
         "    : m3_view_logical_offset(bias_view, 0ul);\n"
         "  ulong bias_stride = bias_view.byte_strides[0];\n"
         "  volatile float sum = 0.0f;\n"
         "  for (ulong channel = 0; channel < channels; ++channel) {\n"
         "    ulong input_offset =\n"
         "      input_base + channel * input_stride;\n"
         "    float value =\n"
         "      m3_load_float(input + input_offset, input_view.dtype);\n"
         "    sum = sum + value;\n"
         "  }\n"
         "  float mean = sum / float(channels);\n"
         "  volatile float variance_sum = 0.0f;\n"
         "  for (ulong channel = 0; channel < channels; ++channel) {\n"
         "    ulong input_offset =\n"
         "      input_base + channel * input_stride;\n"
         "    float value =\n"
         "      m3_load_float(input + input_offset, input_view.dtype);\n"
         "    float centered = value - mean;\n"
         "    volatile float square = centered * centered;\n"
         "    variance_sum = variance_sum + square;\n"
         "  }\n"
         "  float mean_variance = variance_sum / float(channels);\n"
         "  float inverse_standard_deviation =\n"
         "    1.0f / metal::precise::sqrt(mean_variance + epsilon);\n"
         "  for (ulong channel = 0; channel < channels; ++channel) {\n"
         "    ulong flat = row_flat + channel;\n"
         "    ulong input_offset =\n"
         "      input_base + channel * input_stride;\n"
         "    ulong scale_offset =\n"
         "      scale_base + channel * scale_stride;\n"
         "    ulong output_offset =\n"
         "      m3_view_contiguous_offset(output_view, flat);\n"
         "    float value =\n"
         "      m3_load_float(input + input_offset, input_view.dtype);\n"
         "    float scale_value =\n"
         "      m3_load_float(scale + scale_offset, scale_view.dtype);\n"
         "    float centered = value - mean;\n"
         "    float normalized = centered * inverse_standard_deviation;\n"
         "    float result = normalized * scale_value;\n"
         "    if (has_bias != 0u) {\n"
         "      ulong bias_offset =\n"
         "        bias_base + channel * bias_stride;\n"
         "      float bias_value =\n"
         "        m3_load_float(bias + bias_offset, bias_view.dtype);\n"
         "      result = result + bias_value;\n"
         "    }\n"
         "    m3_store_float(output + output_offset, output_view.dtype,\n"
         "                   result);\n"
         "  }\n"
         "}\n";
    NSString *rotary_activation =
        @"kernel void m3_rope(\n"
         "    device const uchar* input [[buffer(0)]],\n"
         "    device const uchar* cosines [[buffer(1)]],\n"
         "    device const uchar* sines [[buffer(2)]],\n"
         "    device uchar* output [[buffer(3)]],\n"
         "    constant M3ViewParameters& input_view [[buffer(4)]],\n"
         "    constant M3ViewParameters& cosines_view [[buffer(5)]],\n"
         "    constant M3ViewParameters& sines_view [[buffer(6)]],\n"
         "    constant M3ViewParameters& output_view [[buffer(7)]],\n"
         "    constant ulong& position_offset [[buffer(8)]],\n"
         "    constant uint& rotary_dimension [[buffer(9)]],\n"
         "    constant uint& mode [[buffer(10)]],\n"
         "    uint gid [[thread_position_in_grid]]) {\n"
         "  ulong vector = ulong(gid);\n"
         "  ulong depth = input_view.shape[3];\n"
         "  if (vector >= input_view.element_count / depth) return;\n"
         "  ulong position = vector % input_view.shape[2];\n"
         "  ulong table_row = position_offset + position;\n"
         "  ulong pair_count = ulong(rotary_dimension) / 2u;\n"
         "  for (ulong pair = 0; pair < pair_count; ++pair) {\n"
         "    ulong first_index = mode == 0u ? pair : pair * 2u;\n"
         "    ulong second_index = mode == 0u\n"
         "      ? pair + pair_count : pair * 2u + 1u;\n"
         "    ulong first_flat = vector * depth + first_index;\n"
         "    ulong second_flat = vector * depth + second_index;\n"
         "    ulong table_flat = table_row * pair_count + pair;\n"
         "    ulong first_offset =\n"
         "      m3_view_logical_offset(input_view, first_flat);\n"
         "    ulong second_offset =\n"
         "      m3_view_logical_offset(input_view, second_flat);\n"
         "    ulong cosine_offset =\n"
         "      m3_view_logical_offset(cosines_view, table_flat);\n"
         "    ulong sine_offset =\n"
         "      m3_view_logical_offset(sines_view, table_flat);\n"
         "    float first =\n"
         "      m3_load_float(input + first_offset, input_view.dtype);\n"
         "    float second =\n"
         "      m3_load_float(input + second_offset, input_view.dtype);\n"
         "    float cosine = m3_load_float(\n"
         "      cosines + cosine_offset, cosines_view.dtype);\n"
         "    float sine =\n"
         "      m3_load_float(sines + sine_offset, sines_view.dtype);\n"
         "    volatile float second_sine = second * sine;\n"
         "    volatile float first_sine = first * sine;\n"
         "    float rotated_first = metal::precise::fma(\n"
         "      first, cosine, -second_sine);\n"
         "    float rotated_second = metal::precise::fma(\n"
         "      second, cosine, first_sine);\n"
         "    ulong first_output =\n"
         "      m3_view_contiguous_offset(output_view, first_flat);\n"
         "    ulong second_output =\n"
         "      m3_view_contiguous_offset(output_view, second_flat);\n"
         "    m3_store_float(output + first_output, output_view.dtype,\n"
         "                   rotated_first);\n"
         "    m3_store_float(output + second_output, output_view.dtype,\n"
         "                   rotated_second);\n"
         "  }\n"
         "  for (ulong index = ulong(rotary_dimension); index < depth;\n"
         "       ++index) {\n"
         "    ulong flat = vector * depth + index;\n"
         "    ulong input_offset =\n"
         "      m3_view_logical_offset(input_view, flat);\n"
         "    ulong output_offset =\n"
         "      m3_view_contiguous_offset(output_view, flat);\n"
         "    float value =\n"
         "      m3_load_float(input + input_offset, input_view.dtype);\n"
         "    m3_store_float(output + output_offset, output_view.dtype,\n"
         "                   value);\n"
         "  }\n"
         "}\n"
         "kernel void m3_gated_silu(\n"
         "    device const uchar* gate [[buffer(0)]],\n"
         "    device const uchar* up [[buffer(1)]],\n"
         "    device uchar* output [[buffer(2)]],\n"
         "    constant M3ViewParameters& gate_view [[buffer(3)]],\n"
         "    constant M3ViewParameters& up_view [[buffer(4)]],\n"
         "    constant M3ViewParameters& output_view [[buffer(5)]],\n"
         "    uint gid [[thread_position_in_grid]]) {\n"
         "  ulong flat = ulong(gid);\n"
         "  if (flat >= output_view.element_count) return;\n"
         "  ulong gate_offset = m3_view_logical_offset(gate_view, flat);\n"
         "  ulong up_offset = m3_view_logical_offset(up_view, flat);\n"
         "  ulong output_offset =\n"
         "    m3_view_contiguous_offset(output_view, flat);\n"
         "  float gate_value =\n"
         "    m3_load_float(gate + gate_offset, gate_view.dtype);\n"
         "  float up_value =\n"
         "    m3_load_float(up + up_offset, up_view.dtype);\n"
         "  float denominator =\n"
         "    1.0f + metal::precise::exp(-gate_value);\n"
         "  float activation = gate_value / denominator;\n"
         "  activation = m3_round_float(gate_view.dtype, activation);\n"
         "  float result = activation * up_value;\n"
         "  m3_store_float(output + output_offset, output_view.dtype,\n"
         "                 result);\n"
         "}\n";

    NSString *source =
        [embedding stringByAppendingString:matrices];

    source = [source stringByAppendingString:linear];
    source = [source stringByAppendingString:rms_norm];
    source = [source stringByAppendingString:layer_norm];
    return [source stringByAppendingString:rotary_activation];
}
